<?php
/**
 * Campaigns (newsletters) list screen.
 *
 * @package SimpleEmailNewsletters
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

$semnews_paged = isset( $_GET['paged'] ) ? max( 1, absint( $_GET['paged'] ) ) : 1; // phpcs:ignore WordPress.Security.NonceVerification.Recommended
$semnews_data  = SEMNEWS_Campaigns::query( array( 'paged' => $semnews_paged, 'per_page' => 20 ) );
$semnews_new_url = admin_url( 'admin.php?page=semnews-campaigns&action=new' );

$semnews_status_labels = array(
	SEMNEWS_Campaigns::STATUS_DRAFT     => __( 'Draft', 'quintessential-newsletters' ),
	SEMNEWS_Campaigns::STATUS_SCHEDULED => __( 'Scheduled', 'quintessential-newsletters' ),
	SEMNEWS_Campaigns::STATUS_SENDING   => __( 'Sending', 'quintessential-newsletters' ),
	SEMNEWS_Campaigns::STATUS_SENT      => __( 'Sent', 'quintessential-newsletters' ),
	SEMNEWS_Campaigns::STATUS_PAUSED    => __( 'Paused', 'quintessential-newsletters' ),
);
?>
<div class="wrap semnews-wrap">
	<h1 class="wp-heading-inline"><?php esc_html_e( 'Newsletters', 'quintessential-newsletters' ); ?></h1>
	<a href="<?php echo esc_url( $semnews_new_url ); ?>" class="page-title-action"><?php esc_html_e( 'Write new', 'quintessential-newsletters' ); ?></a>
	<hr class="wp-header-end" />

	<?php SEMNEWS_Admin::render_notice(); ?>

	<table class="wp-list-table widefat fixed striped">
		<thead>
			<tr>
				<th><?php esc_html_e( 'Subject', 'quintessential-newsletters' ); ?></th>
				<th><?php esc_html_e( 'Status', 'quintessential-newsletters' ); ?></th>
				<th><?php esc_html_e( 'Recipients', 'quintessential-newsletters' ); ?></th>
				<th><?php esc_html_e( 'Sent', 'quintessential-newsletters' ); ?></th>
				<th><?php esc_html_e( 'Created', 'quintessential-newsletters' ); ?></th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<?php if ( empty( $semnews_data['items'] ) ) : ?>
				<tr><td colspan="6"><?php esc_html_e( 'No newsletters yet.', 'quintessential-newsletters' ); ?> <a href="<?php echo esc_url( $semnews_new_url ); ?>"><?php esc_html_e( 'Write your first one.', 'quintessential-newsletters' ); ?></a></td></tr>
			<?php else : ?>
				<?php foreach ( $semnews_data['items'] as $semnews_item ) : ?>
					<?php $semnews_edit_url = admin_url( 'admin.php?page=semnews-campaigns&action=edit&campaign=' . (int) $semnews_item->id ); ?>
					<tr>
						<td>
							<strong><a href="<?php echo esc_url( $semnews_edit_url ); ?>"><?php echo esc_html( $semnews_item->subject ? $semnews_item->subject : __( '(no subject)', 'quintessential-newsletters' ) ); ?></a></strong>
							<?php if ( isset( $semnews_item->type ) && 'auto' === $semnews_item->type ) : ?>
								<span class="semnews-badge-auto" title="<?php esc_attr_e( 'Generated by the automated newsletter', 'quintessential-newsletters' ); ?>"><?php esc_html_e( 'Automated', 'quintessential-newsletters' ); ?></span>
							<?php endif; ?>
						</td>
						<td>
							<span class="semnews-status semnews-status-<?php echo esc_attr( $semnews_item->status ); ?>">
								<?php echo esc_html( isset( $semnews_status_labels[ $semnews_item->status ] ) ? $semnews_status_labels[ $semnews_item->status ] : $semnews_item->status ); ?>
							</span>
						</td>
						<td><?php echo esc_html( number_format_i18n( $semnews_item->total_recipients ) ); ?></td>
						<td>
							<?php
							echo esc_html( number_format_i18n( $semnews_item->sent_count ) );
							if ( $semnews_item->failed_count > 0 ) {
								echo ' <span class="semnews-failed">(' . esc_html( number_format_i18n( $semnews_item->failed_count ) ) . ' ' . esc_html__( 'failed', 'quintessential-newsletters' ) . ')</span>';
							}
							?>
						</td>
						<td>
							<?php echo esc_html( mysql2date( get_option( 'date_format' ), $semnews_item->created_at ) ); ?>
							<?php if ( SEMNEWS_Campaigns::STATUS_SCHEDULED === $semnews_item->status && $semnews_item->scheduled_at ) : ?>
								<br /><span class="description">
									<?php
									/* translators: %s: scheduled date/time. */
									printf( esc_html__( 'sends %s', 'quintessential-newsletters' ), esc_html( get_date_from_gmt( $semnews_item->scheduled_at, get_option( 'date_format' ) . ' ' . get_option( 'time_format' ) ) ) );
									?>
								</span>
							<?php endif; ?>
						</td>
						<td>
							<a href="<?php echo esc_url( $semnews_edit_url ); ?>"><?php echo SEMNEWS_Campaigns::STATUS_SENT === $semnews_item->status ? esc_html__( 'View', 'quintessential-newsletters' ) : esc_html__( 'Edit', 'quintessential-newsletters' ); ?></a>
						</td>
					</tr>
				<?php endforeach; ?>
			<?php endif; ?>
		</tbody>
	</table>

	<?php
	// Pagination: without this, campaigns beyond the first 20 were unreachable.
	$semnews_total_pages = (int) ceil( $semnews_data['total'] / 20 );
	if ( $semnews_total_pages > 1 ) {
		echo '<div class="tablenav bottom"><div class="tablenav-pages">';
		echo wp_kses_post(
			paginate_links(
				array(
					'base'    => add_query_arg( 'paged', '%#%' ),
					'format'  => '',
					'current' => $semnews_paged,
					'total'   => $semnews_total_pages,
				)
			)
		);
		echo '</div></div>';
	}
	?>
</div>
